[build]
  command = "npm run build"
  publish = "public"
  functions = "lambda"

[dev]
  command = "gatsby develop"
  targetPort = 8000

[context.production.environment]
  NODE_VERSION = "14"

[[plugins]]
  package = "@netlify/plugin-nextjs"
